// CREDITS: https://github.com/asciidoctor/docbookrx/blob/master/README.adoc
// User Variables
:name: Daniel Suárez
:handle: danielussen
:fullname: {name} Daniel
:twitter-profile: https://twitter.com/{handle}

// Badges & Tiles
:pulumi-community-url: https://www.pulumi.com/community/
:uorframework-gh-url: https://emporous.io
:containercraft-gh-url: https://github.com/ContainerCraft
:pulumiverse-blog-url: https://www.pulumi.com/blog/2022-03-30-introducing-pulumiverse/
:kubevirt-community-url: https://kubevirt.io/community/
:linkedin-url: https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white
:profile-stats-tile-url: https://github-readme-stats.vercel.app/api?username=usrbinkat&count_private=true&count_private=true&show_icons=true&include_all_commits=true&theme=nightowl&cache_seconds=86400

// Document Settings
:idprefix:
:idseparator: -
:icons: font
//:toc:
//:toclevels: 1

// Begin Document
= {fullname}

++++
<div id="badges">
  <a href="https://www.linkedin.com/in/daniel-su%C3%A1rez-python-developer/">
    <img src="https://img.shields.io/badge/LinkedIn-blue?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn Badge"/>
  </a>
  <a href="https://www.youtube.com/channel/UCaR4Lk0ZYPtws-U5O-Ockpw">
    <img src="https://img.shields.io/badge/YouTube-red?style=for-the-badge&logo=youtube&logoColor=white" alt="Youtube Badge"/>
  </a>
  <a href="https://twitter.com/danielussen">
    <img src="https://img.shields.io/badge/Twitter-blue?style=for-the-badge&logo=twitter&logoColor=white" alt="Twitter Badge"/>
  </a>

</div>
++++

== About Me +

```
daniel@honeypot:/# /usr/bin/daniel --help

             _               _             _       _ 
            (_)      _      | |           (_)     | |
 ____   ____ _ ____ | |_  _ | | ____ ____  _  ____| |
|  _ \ / ___) |  _ \|  _)/ || |/ _  |  _ \| |/ _  ) |
| | | | |   | | | | | |_( (_| ( ( | | | | | ( (/ /| |
| ||_/|_|   |_|_| |_|\___)____|\_||_|_| |_|_|\____)_|
|_|
```
Hello, everyone,

My name is Daniel, and I am a Python Developer, Data Analyst, ETL Developer, creator of RESTful APIs, and an expert in Django Rest Framework. My journey began during my studies in Electronic Engineering at the National Technological University of Argentina (UTN), where I was introduced to the programming language C.

Over time, I have evolved into a multifaceted professional, specializing in Python development and data-related tasks. I excel in leveraging Python's capabilities for ETL (Extract, Transform, Load) processes, enabling seamless data integration and analysis. Additionally, my expertise extends to crafting robust RESTful APIs using Django Rest Framework, ensuring efficient and scalable web applications.

My current focus lies in continuous learning and expanding my skills through diverse ETL projects. I am passionate about leveraging technology to solve complex data challenges and drive meaningful insights for businesses.

Thank you for the opportunity to share a glimpse of my background and expertise. I look forward to contributing my skills and knowledge to your team.

Best regards,
Daniel


== Core Roles +
* {pulumi-community-url}[Pulumi Developer Relations - Community Engineer]

== Projects +
* {uorframework-gh-url}[Emporous.io]
* {containercraft-gh-url}[ContainerCraft.io]

== Community +
* {pulumiverse-blog-url}[Pulumiverse]
* {kubevirt-community-url}[KubeVirt Community]

== Favorite Technologies +
:siderolabs-gh-url: https://www.siderolabs.com/
:kubevirt-site-url: https://kubevirt.io
:rook-ceph-url: https://rook.github.io/docs/rook/latest/
:cloudctl-gh-url: https://github.com/CloudCtl/cloudctl
:kuma-site-url: https://kuma.io/
:microk8s-site-url: https://microk8s.io/
:pulumi-site-url: https://pulumi.com
:clusterapi-url: https://cluster-api.sigs.k8s.io/

* *VIM All The Things!!*
* link:{kuma-site-url}[Kuma Mesh]
* link:{uorframework-gh-url}[Emporous.io]
* link:{rook-ceph-url}[Rook CEPH]
* link:{clusterapi-url}[Cluster API]
* link:{kubevirt-site-url}[KubeVirt]
* link:{cloudctl-gh-url}[CloudCtl Pod]
* link:{siderolabs-gh-url}[Sidero Labs - Talos] / link:{microk8s-site-url}[Microk8s]
* link:{pulumi-site-url}[Pulumi]
* Python
* Golang
* Typescript

image:{profile-stats-tile-url}[] +
